live_loop :melody do
  # ### <music21.stream.Measure 1 offset=0.0>
          play :fs5
          sleep 2.0
          play :e5
          sleep 2.0
  # ### <music21.stream.Measure 2 offset=4.0>
          play :d5
          sleep 2.0
          play :cs5
          sleep 2.0
  # ### <music21.stream.Measure 3 offset=8.0>
          play :b4
          sleep 2.0
          play :a4
          sleep 2.0
  # ### <music21.stream.Measure 4 offset=12.0>
          play :b4
          sleep 2.0
          play :cs5
          sleep 2.0
  # ### <music21.stream.Measure 5 offset=16.0>
          play_chord [:d5, :fs5]
          sleep 2.0
          play_chord [:cs5, :e5]
          sleep 2.0
  # ### <music21.stream.Measure 6 offset=20.0>
          play_chord [:b4, :d5]
          sleep 2.0
          play_chord [:a4, :cs5]
          sleep 2.0
  # ### <music21.stream.Measure 7 offset=24.0>
          play_chord [:g4, :b4]
          sleep 2.0
          play_chord [:fs4, :a4]
          sleep 2.0
  # ### <music21.stream.Measure 8 offset=28.0>
          play_chord [:g4, :b4]
          sleep 2.0
          play_chord [:a4, :cs5]
          sleep 2.0
  # ### <music21.stream.Measure 9 offset=32.0>
  # ### <music21.stream.Measure 10 offset=36.0>
  # ### <music21.stream.Measure 11 offset=40.0>
  # ### <music21.stream.Measure 12 offset=44.0>
  # ### <music21.stream.Measure 13 offset=48.0>
          play :a5
          sleep 0.5
          play :fs5
          sleep 0.25
          play :g5
          sleep 0.25
          play :a5
          sleep 0.5
          play :fs5
          sleep 0.25
          play :g5
          sleep 0.25
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :e5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :g5
          sleep 0.25
  # ### <music21.stream.Measure 14 offset=52.0>
          play :fs5
          sleep 0.5
          play :d5
          sleep 0.25
          play :e5
          sleep 0.25
          play :fs5
          sleep 0.5
          play :fs4
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
          play :a4
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
  # ### <music21.stream.Measure 15 offset=56.0>
          play :g4
          sleep 0.5
          play :b4
          sleep 0.25
          play :a4
          sleep 0.25
          play :g4
          sleep 0.5
          play :fs4
          sleep 0.25
          play :e4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :e4
          sleep 0.25
          play :d4
          sleep 0.25
          play :e4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
  # ### <music21.stream.Measure 16 offset=60.0>
          play :g4
          sleep 0.5
          play :b4
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.5
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :cs5
          sleep 0.25
          play :b4
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :e5
          sleep 0.25
          play :fs5
          sleep 0.25
  # ### <music21.stream.Measure 17 offset=64.0>
          play_chord [:fs5, :a5]
          sleep 0.5
          play_chord [:d5, :fs5]
          sleep 0.25
          play_chord [:e5, :g5]
          sleep 0.25
          play_chord [:fs5, :a5]
          sleep 0.5
          play_chord [:d5, :fs5]
          sleep 0.25
          play_chord [:e5, :g5]
          sleep 0.25
          play_chord [:cs5, :a5]
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :e5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :g5
          sleep 0.25
  # ### <music21.stream.Measure 18 offset=68.0>
          play_chord [:d5, :fs5]
          sleep 0.5
          play_chord [:b4, :d5]
          sleep 0.25
          play_chord [:cs5, :e5]
          sleep 0.25
          play_chord [:d5, :fs5]
          sleep 0.5
          play :fs4
          sleep 0.25
          play :g4
          sleep 0.25
          play_chord [:fs4, :a4]
          sleep 0.25
          play :b4
          sleep 0.25
          play :a4
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
          play :d5
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
  # ### <music21.stream.Measure 19 offset=72.0>
          play_chord [:g4, :b4]
          sleep 0.5
          play_chord [:b4, :d5]
          sleep 0.25
          play_chord [:a4, :cs5]
          sleep 0.25
          play_chord [:g4, :b4]
          sleep 0.5
          play :a4
          sleep 0.25
          play :g4
          sleep 0.25
          play_chord [:fs4, :a4]
          sleep 0.25
          play :g4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
  # ### <music21.stream.Measure 20 offset=76.0>
          play_chord [:g4, :b4]
          sleep 0.5
          play_chord [:b4, :d5]
          sleep 0.25
          play_chord [:a4, :cs5]
          sleep 0.25
          play_chord [:b4, :d5]
          sleep 0.5
          play :cs5
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :e5
          sleep 0.25
          play :d5
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
  # ### <music21.stream.Measure 21 offset=80.0>
  # ### <music21.stream.Measure 22 offset=84.0>
  # ### <music21.stream.Measure 23 offset=88.0>
  # ### <music21.stream.Measure 24 offset=92.0>
  # ### <music21.stream.Measure 25 offset=96.0>
  # ### <music21.stream.Measure 26 offset=100.0>
  # ### <music21.stream.Measure 27 offset=104.0>
  # ### <music21.stream.Measure 28 offset=108.0>
  # ### <music21.stream.Measure 29 offset=112.0>
          play :fs5
          sleep 1.0
          play_chord [:d5, :d6]
          sleep 0.5
          play :fs5
          sleep 0.5
          play :fs5
          sleep 0.5
          play :g5
          sleep 0.5
          play_chord [:cs5, :fs5, :cs6]
          sleep 0.5
          play :e5
          sleep 0.5
  # ### <music21.stream.Measure 30 offset=116.0>
          play :d5
          sleep 1.0
          play_chord [:b4, :b5]
          sleep 0.5
          play :d5
          sleep 0.5
          play :d5
          sleep 0.5
          play :e5
          sleep 0.5
          play_chord [:a4, :d5, :a5]
          sleep 0.5
          play :cs5
          sleep 0.5
  # ### <music21.stream.Measure 31 offset=120.0>
          play :b4
          sleep 1.0
          play_chord [:g4, :g5]
          sleep 1.0
          play_chord [:fs5, :d6]
          sleep 1.0
          play_chord [:d5, :a5]
          sleep 1.0
  # ### <music21.stream.Measure 32 offset=124.0>
          play_chord [:d5, :b5]
          sleep 1.0
          play_chord [:b4, :g5]
          sleep 1.0
          play_chord [:cs5, :a5]
          sleep 1.0
          play_chord [:fs4, :fs5]
          sleep 0.5
          play_chord [:g4, :g5]
          sleep 0.5
  # ### <music21.stream.Measure 33 offset=128.0>
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :d5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :a5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :a4
          sleep 0.25
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :b5
          sleep 0.25
          play :b4
          sleep 0.25
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :g5
          sleep 0.25
          play :g4
          sleep 0.25
  # ### <music21.stream.Measure 34 offset=132.0>
          play :fs5
          sleep 0.25
          play :fs4
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :b4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :fs5
          sleep 0.25
          play :fs4
          sleep 0.25
          play :g5
          sleep 0.25
          play :g4
          sleep 0.25
          play :fs5
          sleep 0.25
          play :fs4
          sleep 0.25
          play :e5
          sleep 0.25
          play :e4
          sleep 0.25
  # ### <music21.stream.Measure 35 offset=136.0>
          play :d5
          sleep 0.25
          play :d4
          sleep 0.25
          play :g4
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :b4
          sleep 0.25
          play :g4
          sleep 0.25
          play :d4
          sleep 0.25
          play :d5
          sleep 0.25
          play :d4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :a4
          sleep 0.25
          play :fs5
          sleep 0.25
          play :fs4
          sleep 0.25
          play :a4
          sleep 0.25
          play :d5
          sleep 0.25
  # ### <music21.stream.Measure 36 offset=140.0>
          play :g5
          sleep 0.25
          play :g4
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :b5
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :g5
          sleep 0.25
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :e5
          sleep 0.25
          play :b5
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs6
          sleep 0.25
          play :cs5
          sleep 0.25
  # ### <music21.stream.Measure 37 offset=144.0>
          play :d6
          sleep 0.25
          play :d5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :a5
          sleep 0.25
          play :d6
          sleep 0.25
          play :a5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :d6
          sleep 0.25
          play :d5
          sleep 0.25
          play :e5
          sleep 0.25
          play :a5
          sleep 0.25
          play :cs6
          sleep 0.25
          play :cs5
          sleep 0.25
          play :e5
          sleep 0.25
          play :a5
          sleep 0.25
  # ### <music21.stream.Measure 38 offset=148.0>
          play :cs6
          sleep 0.25
          play :cs5
          sleep 0.25
          play :d5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :b5
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :b5
          sleep 0.25
          play :b4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :fs5
          sleep 0.25
  # ### <music21.stream.Measure 39 offset=152.0>
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :g5
          sleep 0.25
          play :g4
          sleep 0.25
          play :b4
          sleep 0.25
          play :d5
          sleep 0.25
          play :g5
          sleep 0.25
          play :g4
          sleep 0.25
          play :a4
          sleep 0.25
          play :d5
          sleep 0.25
          play :fs5
          sleep 0.25
          play :fs4
          sleep 0.25
          play :a4
          sleep 0.25
          play :d5
          sleep 0.25
  # ### <music21.stream.Measure 40 offset=156.0>
          play :fs5
          sleep 0.25
          play :fs4
          sleep 0.25
          play :g4
          sleep 0.25
          play :b4
          sleep 0.25
          play :e5
          sleep 0.25
          play :e4
          sleep 0.25
          play :g5
          sleep 0.25
          play :g4
          sleep 0.25
          play :a5
          sleep 0.25
          play :a4
          sleep 0.25
          play :cs5
          sleep 0.25
          play :e5
          sleep 0.25
          play_chord [:b4, :b5]
          sleep 0.5
          play_chord [:cs5, :cs6]
          sleep 0.5
  # ### <music21.stream.Measure 41 offset=160.0>
          play_chord [:d5, :fs5, :a5, :d6]
          sleep 1.0
          play_chord [:fs4, :a4, :d5]
          sleep 1.0
          play_chord [:cs4, :e4, :a4, :cs5]
          sleep 0.75
          play_chord [:e5, :cs6]
          sleep 0.25
          play :a5
          sleep 0.25
          play :e5
          sleep 0.25
          play :cs5
          sleep 0.25
          play :e5
          sleep 0.25
  # ### <music21.stream.Measure 42 offset=164.0>
          play_chord [:b4, :d5, :fs5, :b5]
          sleep 1.0
          play_chord [:d4, :fs4, :b4]
          sleep 1.0
          play_chord [:a3, :cs4, :fs4, :a4]
          sleep 0.75
          play_chord [:cs5, :a5]
          sleep 0.25
          play :fs5
          sleep 0.25
          play :cs5
          sleep 0.25
          play :a4
          sleep 0.25
          play :cs5
          sleep 0.25
  # ### <music21.stream.Measure 43 offset=168.0>
          play_chord [:g4, :b4, :d5, :g5]
          sleep 1.0
          play_chord [:g3, :b3, :d4, :g4]
          sleep 1.0
          play_chord [:fs3, :a3, :d4, :fs4]
          sleep 1.0
          play_chord [:fs4, :a4, :d5, :fs5]
          sleep 1.0
  # ### <music21.stream.Measure 44 offset=172.0>
          play_chord [:g3, :b3, :d4, :g4]
          sleep 1.0
          play_chord [:b4, :d5, :g5, :b5]
          sleep 1.0
          play_chord [:cs4, :e4, :a4, :cs5]
          sleep 0.5
          play_chord [:e4, :a4, :cs5, :e5]
          sleep 0.5
          play_chord [:a4, :cs5, :e5, :a5]
          sleep 0.5
          play_chord [:cs5, :e5, :a5, :cs6]
          sleep 0.5
  # ### <music21.stream.Measure 45 offset=176.0>
          play_chord [:fs5, :d6, :fs6]
          sleep 4.0
  # ### <music21.stream.Measure 46 offset=180.0>
          play_chord [:d6, :d7]
          sleep 2.0
          stop
  end
  live_loop :melody do
  # ### <music21.stream.Measure 1 offset=0.0>
          play :d3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :fs4
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :cs4
          sleep 0.5
  # ### <music21.stream.Measure 2 offset=4.0>
          play :b2
          sleep 0.5
          play :fs3
          sleep 0.5
          play :b3
          sleep 0.5
          play :d4
          sleep 0.5
          play :fs2
          sleep 0.5
          play :cs3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :a3
          sleep 0.5
  # ### <music21.stream.Measure 3 offset=8.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :b3
          sleep 0.5
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :fs3
          sleep 0.5
  # ### <music21.stream.Measure 4 offset=12.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :b3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :cs4
          sleep 0.5
  # ### <music21.stream.Measure 5 offset=16.0>
          play :d3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :fs4
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :cs4
          sleep 0.5
  # ### <music21.stream.Measure 6 offset=20.0>
          play :b2
          sleep 0.5
          play :fs3
          sleep 0.5
          play :b3
          sleep 0.5
          play :d4
          sleep 0.5
          play :fs2
          sleep 0.5
          play :cs3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :a3
          sleep 0.5
  # ### <music21.stream.Measure 7 offset=24.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :b3
          sleep 0.5
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :fs3
          sleep 0.5
  # ### <music21.stream.Measure 8 offset=28.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :b3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :cs4
          sleep 0.5
  # ### <music21.stream.Measure 9 offset=32.0>
          play :d3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :a3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 10 offset=36.0>
          play :b2
          sleep 0.5
          play :fs3
          sleep 0.5
          play :b3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :fs2
          sleep 0.5
          play :cs3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :cs3
          sleep 0.5
  # ### <music21.stream.Measure 11 offset=40.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
  # ### <music21.stream.Measure 12 offset=44.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 13 offset=48.0>
          play :d3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :a3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 14 offset=52.0>
          play :b2
          sleep 0.5
          play :fs3
          sleep 0.5
          play :b3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :fs2
          sleep 0.5
          play :cs3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :cs3
          sleep 0.5
  # ### <music21.stream.Measure 15 offset=56.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
  # ### <music21.stream.Measure 16 offset=60.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 17 offset=64.0>
          play :d3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :a3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 18 offset=68.0>
          play :b2
          sleep 0.5
          play :fs3
          sleep 0.5
          play :b3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :fs2
          sleep 0.5
          play :cs3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :cs3
          sleep 0.5
  # ### <music21.stream.Measure 19 offset=72.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
  # ### <music21.stream.Measure 20 offset=76.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 21 offset=80.0>
          play :d3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :a3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :e3
          sleep 0.5
  # ### <music21.stream.Measure 22 offset=84.0>
          play :b2
          sleep 0.5
          play :fs3
          sleep 0.5
          play :b3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :fs2
          sleep 0.5
          play :cs3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :cs3
          sleep 0.5
  # ### <music21.stream.Measure 23 offset=88.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
  # ### <music21.stream.Measure 24 offset=92.0>
          play :g2
          sleep 0.5
          play :d3
          sleep 0.5
          play :g3
          sleep 0.5
          play :d3
          sleep 0.5
          play :a2
          sleep 0.5
          play :e3
          sleep 0.5
          play :a3
          sleep 0.5
          play :cs4
          sleep 0.5
  # ### <music21.stream.Measure 25 offset=96.0>
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :d4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :d4
          sleep 0.25
          play :a3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 26 offset=100.0>
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b3
          sleep 0.25
          play :d4
          sleep 0.25
          play :b3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :a3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
  # ### <music21.stream.Measure 27 offset=104.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
          play :d3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
  # ### <music21.stream.Measure 28 offset=108.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 29 offset=112.0>
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :d4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :d4
          sleep 0.25
          play :a3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 30 offset=116.0>
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b3
          sleep 0.25
          play :d4
          sleep 0.25
          play :b3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :a3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
  # ### <music21.stream.Measure 31 offset=120.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
          play :d3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
  # ### <music21.stream.Measure 32 offset=124.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 33 offset=128.0>
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :d4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :d4
          sleep 0.25
          play :a3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 34 offset=132.0>
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b3
          sleep 0.25
          play :d4
          sleep 0.25
          play :b3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :a3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
  # ### <music21.stream.Measure 35 offset=136.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
          play :d3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
  # ### <music21.stream.Measure 36 offset=140.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 37 offset=144.0>
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :d4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :d4
          sleep 0.25
          play :a3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 38 offset=148.0>
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b3
          sleep 0.25
          play :d4
          sleep 0.25
          play :b3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :a3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
  # ### <music21.stream.Measure 39 offset=152.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
          play :d3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
  # ### <music21.stream.Measure 40 offset=156.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 41 offset=160.0>
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :d4
          sleep 0.25
          play :fs4
          sleep 0.25
          play :d4
          sleep 0.25
          play :a3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 42 offset=164.0>
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b3
          sleep 0.25
          play :d4
          sleep 0.25
          play :b3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :b2
          sleep 0.25
          play :fs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :a3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :cs3
          sleep 0.25
          play :fs2
          sleep 0.25
          play :cs3
          sleep 0.25
  # ### <music21.stream.Measure 43 offset=168.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
          play :d3
          sleep 0.25
          play :fs3
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :d2
          sleep 0.25
          play :a2
          sleep 0.25
  # ### <music21.stream.Measure 44 offset=172.0>
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :g3
          sleep 0.25
          play :b3
          sleep 0.25
          play :g3
          sleep 0.25
          play :d3
          sleep 0.25
          play :g2
          sleep 0.25
          play :d3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
          play :a3
          sleep 0.25
          play :cs4
          sleep 0.25
          play :a3
          sleep 0.25
          play :e3
          sleep 0.25
          play :a2
          sleep 0.25
          play :e3
          sleep 0.25
  # ### <music21.stream.Measure 45 offset=176.0>
          play :d2
          sleep 0.5
          play :a2
          sleep 0.5
          play :d3
          sleep 0.5
          play :fs3
          sleep 0.5
          play :a3
          sleep 0.5
          play :d4
          sleep 0.5
          play :fs4
          sleep 0.5
          play :a4
          sleep 0.5
  # ### <music21.stream.Measure 46 offset=180.0>
          play :d5
          sleep 0.5
          play :fs5
          sleep 0.5
          play :a5
          sleep 1.0
          play :d5
          sleep 2.0
          stop
  end
